# Generated by Django 5.1.2 on 2024-11-05 10:40

import django.db.models.deletion
import pathlib
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_alter_diaryentry_options_diaryentry_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('entries', 'Diary Entries'), ('time_periods', 'Time Periods'), ('streaks', 'Time Travel Streaks'), ('special', 'Special Achievements')], max_length=20)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/mnt/c/Users/amail/OneDrive/Documents/Support/varshini/repo/time_traveller_diary/diary_project/achievement'))),
                ('required_entries', models.IntegerField(default=0)),
                ('required_time_periods', models.IntegerField(default=0)),
                ('required_streak', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'required_entries', 'required_time_periods'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_entries', models.IntegerField(default=0)),
                ('unique_time_periods', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_entry_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
