# Generated by Django 5.1.2 on 2024-11-07 04:06

import diary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0007_achievement_userprogress_userachievement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=diary.models.user_directory_path
            ),
        ),
    ]
